Reserved Token IDs
mobilecoinfoundation/mcips pull request #45
Opened 2022-07-15 01:30 UTC by jcape

[Rendered Proposal](https://github.com/jcape/mcips/blob/reserved-token-ids/text/0045-reserved-token-ids.md)

2022-07-22 21:25 UTC, nick-mobilecoin approved these changes

2022-07-22 21:25 UTC, nick-mobilecoin commented on text/0045-reserved-token-ids.md
> +
I would think that we would want to allow main net token ids on the test net in order to better simulate tokens on mainnet, prior to them being on mainnet.
Is the desire that one spins up their own local network for these kind of tests and sanity checks?

2022-07-25 17:41 UTC, garbageslam requested changes
I am worried that this compromises our ability to properly test clients in testnet before we go live in mainnet with important synthetic assets.

I think this proposal should be at a minimum be reworked to explain how clients are supposed to be tested if we adopt this proposal. I think this proposal is non-viable because of the difficulty it creates for this.

I think we should also have a more serious discussion of the alternatives in rationale and alternatives. There are easy ways to handle "de-confliction" of networks, which is an important problem that affects all features and not just confidential tokens. Instead of fragmenting configuration across all networks maybe we should come up with unified way to deal with de-confliction, and then everything else will become simpler.

2022-07-25 21:15 UTC, garbageslam commented
I posted a proposal here to explain what I have in mind: https://github.com/mobilecoinfoundation/mcips/pull/49

What I would like is that, token ids that appear in prod are okay to appear in test and dev, and token ids that appear in test are okay to appear in dev. This allows that we can roll out a specific new token id through testing at each layer of the system before we go live, and we don't need to have network-specific token metadata.

2023-07-05 12:42 UTC, closed without merging